### ISSUE TITLE
Portability

### ISSUE THREAD

**Issue by anon-lestat** [madaidan/sandbox-app-launcher#9]
sandbox-app-launcher uses adduser which is debian-specific. Its important to change that for portability.

**Comment by adrelanos** [comment]
Not sure @madaidan or @Whonix will be considered upstream. Up to @madaidan.

* For Debian: It should stay adduser.
* For any other operating systems:
  * As for developing for, testing on other operating systems, I don't think we have a [Contributor](https://www.whonix.org/wiki/Contribute#Contributor) and I don't know if @madaidan wants to do that. I won't do that at this time.
  * I guess [patches welcome](https://www.whonix.org/wiki/Reporting_Bugs#Contributions).
    * I would probably merge a patch that keeps adduser on Debian (based) systems and implements this otherwise on non-Debian systems.

**Comment by anon-lestat** [comment]
I wrote this issue after telling madaidan about it. He said i should make an issue.

**Comment by madaidan** [comment]
> For Debian: It should stay adduser.

Why? I think sandbox-app-launcher should be distro-agnostic. We could switch to `useradd` and it should be effectively the same.

**Comment by adrelanos** [comment]
> > For Debian: It should stay adduser.
> 
> Why? I think sandbox-app-launcher should be distro-agnostic. We could switch to `useradd` and it should be effectively the same.

Quote http://manpages.debian.org/adduser

> by default choosing Debian policy conformant UID and GID values

> By default, each user in Debian GNU/Linux is given a corresponding group with the same name. Usergroups allow group writable directories to be easily maintained by placing the appropriate users in the new group, setting the set-group-ID bit in the directory, and ensuring that all users use a umask of 002.

> adduser.conf

I suggest an if/else.
